x-build-configuration: &build-configuration
  build:
    context: ./
    dockerfile: ./docker/Dockerfile
    target: build
  restart: "no"
  profiles:
    - build
  volumes:
    - ./:/opt/src:ro
    - ./LICENSE:/opt/build/LICENSE:ro
    - ./bin:/opt/build/bin:ro
    - ./build:/opt/build/build:ro
    - ./src:/opt/build/src:ro
    - ./build/output:/opt/build/build/output:rw
    - ./build/cache:/opt/build/build/cache:rw
  working_dir: /opt/build
  environment:
    - UDPTUNNEL_ARCH=${UDPTUNNEL_ARCH:-}

services:
  build:
    <<: *build-configuration
    command: ./bin/build.sh build
  clean:
    <<: *build-configuration
    command: ./bin/build.sh clean
  all:
    <<: *build-configuration
    command: ./bin/build.sh all
  debug:
    <<: *build-configuration
    command: ./bin/build.sh debug
  release:
    <<: *build-configuration
    command: ./bin/build.sh release
  
  udptunnel:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: compose
    restart: "no"
    ports:
      - ${UDPTUNNEL_SOURCE_PORT:-65535}:${UDPTUNNEL_SOURCE_PORT:-65535}
    environment:
      - UDPTUNNEL_MODE=${UDPTUNNEL_MODE:-}
      - UDPTUNNEL_SOURCE_HOST=${UDPTUNNEL_SOURCE_HOST:-}
      - UDPTUNNEL_SOURCE_PORT=${UDPTUNNEL_SOURCE_PORT:-}
      - UDPTUNNEL_DESTINATION_HOST=${UDPTUNNEL_DESTINATION_HOST:-}
      - UDPTUNNEL_DESTINATION_PORT=${UDPTUNNEL_DESTINATION_PORT:-}
      - UDPTUNNEL_TIMEOUT=${UDPTUNNEL_TIMEOUT:-}
      - UDPTUNNEL_VERBOSE=${UDPTUNNEL_VERBOSE:-}
    networks:
      - udptunnel
networks:
  udptunnel:
    external: false
    
